### ISSUE TITLE
Change/improve default wayland display detection

### ISSUE THREAD

**Issue by mangas** [flathub/it.fabiodistasio.AntaresSQL#10]
Some wayland implementations, at least weston and sway seem to avoid the wayland-0 identifier. Would be cool to maybe either try both or grab one that's available as a fallback in case the env var is not set? 

https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/486

I think it's probably worth setting the ozone platform to auto and keep the nvidia workaround. It should behave pretty much the same but this will avoid using x11 if wayland is available on a different display

**Comment by mangas** [comment]
Just adding `--ozone-platform-hint=auto` without changing anything immediately helps with wayland even though now the log is misleading.

@Fabio286 thoughts? I can open up a PR if you like.

```
diff --git a/startantares b/startantares
index a611ddb..db0c4f5 100644
--- a/startantares
+++ b/startantares
@@ -3,7 +3,7 @@
 FLATPAK_ID=${FLATPAK_ID:-it.fabiodistasio.AntaresSQL}
 FEATURES="UseSkiaRenderer, WaylandWindowDecorations"
 TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID}"
-declare -a FLAGS=(--enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist)
+declare -a FLAGS=(--enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist --ozone-platform-hint=auto)

 if [[ $XDG_SESSION_TYPE == "wayland" ]]
 then
@@ -27,4 +27,4 @@ fi

 FLAGS+=(--enable-features="${FEATURES}")
 echo "Passing the following arguments to Electron:" "${FLAGS[@]}"
-zypak-wrapper /app/main/antares "${FLAGS[@]}" "$@"
\ No newline at end of file
+zypak-wrapper /app/main/antares "${FLAGS[@]}" "$@"
```

**Comment by Fabio286** [comment]
> 
> @Fabio286 thoughts? I can open up a PR if you like.
> 
Go ahead 😁

**Comment by mangas** [comment]
@Fabio286 I've opened https://github.com/flathub/it.fabiodistasio.AntaresSQL/pull/11, I've been almost this exact configuration for a bit and seems to be fine. I have also built it from master with the newer versions of electron, seemed to work fine as well. Might be worth trying out and tagging if it's all good
